server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: library

  data:
    web:
      pageable:
        one-indexed-parameters: true

  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library_management1
    username: root
    password: 752004

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  access-token-expiration: 900000  
  refresh-token-expiration: 604800000
  secret: 9f8c7d6a5b4c3e2f1a0d9c8b7e6f5a4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8