server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: library

  data:
    web:
      pageable:
        one-indexed-parameters: true

  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library_management1?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 752004

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true